# Generated by Django 4.2.9 on 2024-01-08 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WorkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobTitle", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("countryOfWork", models.CharField(max_length=255)),
                (
                    "workedFrom",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "workedUntil",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("description", models.TextField()),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs_board.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs_board.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("levelOfEducation", models.CharField(max_length=255)),
                ("fieldOfStudy", models.CharField(max_length=255)),
                ("schoolName", models.CharField(max_length=255)),
                ("countryOfStudy", models.CharField(max_length=255)),
                (
                    "studiedFrom",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "studiedUntil",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs_board.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phoneNumber", models.CharField(max_length=20)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs_board.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("streetAddress", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postCode", models.CharField(max_length=20)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs_board.resume",
                    ),
                ),
            ],
        ),
    ]
