# Generated by Django 4.2.4 on 2024-01-07 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobs_board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userresume", name="countryOfStudy",),
        migrations.RemoveField(model_name="userresume", name="fieldOfStudy",),
        migrations.RemoveField(model_name="userresume", name="levelOfEducation",),
        migrations.RemoveField(model_name="userresume", name="schoolName",),
        migrations.RemoveField(model_name="userresume", name="studiedFrom",),
        migrations.RemoveField(model_name="userresume", name="studiedUntil",),
        migrations.AddField(
            model_name="userresume",
            name="educationEntries",
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
