# Generated by Django 4.2.9 on 2024-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs_board", "0002_alter_education_studiedfrom"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("register_type", models.CharField(max_length=10)),
                ("company", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
