# Generated by Django 4.2.4 on 2024-01-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs_board", "0002_remove_userresume_countryofstudy_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userresume", name="educationEntries",),
        migrations.CreateModel(
            name="EducationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("levelOfEducation", models.CharField(max_length=255)),
                ("fieldOfStudy", models.CharField(max_length=255)),
                ("schoolName", models.CharField(max_length=255)),
                ("countryOfStudy", models.CharField(max_length=255)),
                ("studiedFrom", models.DateField(blank=True, null=True)),
                ("studiedUntil", models.DateField(blank=True, null=True)),
                (
                    "user_resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs_board.userresume",
                    ),
                ),
            ],
        ),
    ]
